services:
#    tellaw_sunshine_admin.example:
#        class: Tellaw\SunshineAdminBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
  sunshine.context_service:
    class: Tellaw\SunshineAdminBundle\Services\ContextService

  sunshine.configuration-reader_service:
    class: Tellaw\SunshineAdminBundle\Services\ConfigurationReaderService

  sunshine.crud_service:
    class: Tellaw\SunshineAdminBundle\Services\CrudService
    arguments: ["@doctrine.orm.entity_manager", "@sunshine.configuration-reader_service"]

